handlers = java.util.logging.ConsoleHandler
.level = INFO

java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.formatter = jason.runtime.MASConsoleLogFormatter

java.level = OFF
javax.level = OFF
sun.level = OFF
jade.level = OFF
